"""Initial auth audit schema

Revision ID: c32b18ad89df
Revises: 
Create Date: 2026-02-03 03:09:46.407066+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c32b18ad89df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('authentication_method', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_service'
    )
    op.create_index('ix_audit_logs_composite_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False, schema='auth_service')
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False, schema='auth_service')
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False, schema='auth_service')
    op.create_index('ix_audit_logs_organization_id', 'audit_logs', ['organization_id'], unique=False, schema='auth_service')
    op.create_index('ix_audit_logs_success', 'audit_logs', ['success'], unique=False, schema='auth_service')
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False, schema='auth_service')
    op.create_table('session_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_service'
    )
    op.create_index('ix_session_history_composite_user_created', 'session_history', ['user_id', 'created_at'], unique=False, schema='auth_service')
    op.create_index('ix_session_history_created_at', 'session_history', ['created_at'], unique=False, schema='auth_service')
    op.create_index('ix_session_history_expired_at', 'session_history', ['expired_at'], unique=False, schema='auth_service')
    op.create_index('ix_session_history_organization_id', 'session_history', ['organization_id'], unique=False, schema='auth_service')
    op.create_index('ix_session_history_session_id', 'session_history', ['session_id'], unique=True, schema='auth_service')
    op.create_index('ix_session_history_user_id', 'session_history', ['user_id'], unique=False, schema='auth_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_history_user_id', table_name='session_history', schema='auth_service')
    op.drop_index('ix_session_history_session_id', table_name='session_history', schema='auth_service')
    op.drop_index('ix_session_history_organization_id', table_name='session_history', schema='auth_service')
    op.drop_index('ix_session_history_expired_at', table_name='session_history', schema='auth_service')
    op.drop_index('ix_session_history_created_at', table_name='session_history', schema='auth_service')
    op.drop_index('ix_session_history_composite_user_created', table_name='session_history', schema='auth_service')
    op.drop_table('session_history', schema='auth_service')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs', schema='auth_service')
    op.drop_index('ix_audit_logs_success', table_name='audit_logs', schema='auth_service')
    op.drop_index('ix_audit_logs_organization_id', table_name='audit_logs', schema='auth_service')
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs', schema='auth_service')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs', schema='auth_service')
    op.drop_index('ix_audit_logs_composite_user_created', table_name='audit_logs', schema='auth_service')
    op.drop_table('audit_logs', schema='auth_service')
    # ### end Alembic commands ###
