"""Initial credential template schema

Revision ID: 1d669d3ded39
Revises: 
Create Date: 2026-02-03 01:43:38.947125+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d669d3ded39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credential_type', sa.String(length=255), nullable=False),
    sa.Column('vct', sa.Text(), nullable=False),
    sa.Column('doctype', sa.Text(), nullable=True),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('privacy_posture', sa.String(length=30), nullable=False),
    sa.Column('selective_disclosure_fields', sa.JSON(), nullable=False),
    sa.Column('derived_attributes', sa.JSON(), nullable=False),
    sa.Column('display_style', sa.JSON(), nullable=False),
    sa.Column('validity_rules', sa.JSON(), nullable=False),
    sa.Column('issuer_requirements', sa.JSON(), nullable=False),
    sa.Column('supported_formats', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='credential_template_service'
    )
    op.create_index(op.f('ix_credential_template_service_credential_templates_organization_id'), 'credential_templates', ['organization_id'], unique=False, schema='credential_template_service')
    op.create_index(op.f('ix_credential_template_service_credential_templates_status'), 'credential_templates', ['status'], unique=False, schema='credential_template_service')
    op.create_index('ix_credential_templates_credential_type', 'credential_templates', ['credential_type'], unique=False, schema='credential_template_service')
    op.create_index('ix_credential_templates_org_status', 'credential_templates', ['organization_id', 'status'], unique=False, schema='credential_template_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credential_templates_org_status', table_name='credential_templates', schema='credential_template_service')
    op.drop_index('ix_credential_templates_credential_type', table_name='credential_templates', schema='credential_template_service')
    op.drop_index(op.f('ix_credential_template_service_credential_templates_status'), table_name='credential_templates', schema='credential_template_service')
    op.drop_index(op.f('ix_credential_template_service_credential_templates_organization_id'), table_name='credential_templates', schema='credential_template_service')
    op.drop_table('credential_templates', schema='credential_template_service')
    # ### end Alembic commands ###
