# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_service_pb2 as auth__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """AuthService handles session management and user authentication state.
    This is the hottest internal service — called on every authenticated request
    from the gateway middleware.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateSession = channel.unary_unary(
                '/marty.ui.auth.v1.AuthService/ValidateSession',
                request_serializer=auth__service__pb2.ValidateSessionRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ValidateSessionResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/marty.ui.auth.v1.AuthService/CreateSession',
                request_serializer=auth__service__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=auth__service__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.InvalidateSession = channel.unary_unary(
                '/marty.ui.auth.v1.AuthService/InvalidateSession',
                request_serializer=auth__service__pb2.InvalidateSessionRequest.SerializeToString,
                response_deserializer=auth__service__pb2.InvalidateSessionResponse.FromString,
                _registered_method=True)
        self.GetAuthStatus = channel.unary_unary(
                '/marty.ui.auth.v1.AuthService/GetAuthStatus',
                request_serializer=auth__service__pb2.GetAuthStatusRequest.SerializeToString,
                response_deserializer=auth__service__pb2.AuthStatusResponse.FromString,
                _registered_method=True)
        self.CredentialVerified = channel.unary_unary(
                '/marty.ui.auth.v1.AuthService/CredentialVerified',
                request_serializer=auth__service__pb2.CredentialVerifiedRequest.SerializeToString,
                response_deserializer=auth__service__pb2.CredentialVerifiedResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.auth.v1.AuthService/HealthCheck',
                request_serializer=auth__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=auth__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """AuthService handles session management and user authentication state.
    This is the hottest internal service — called on every authenticated request
    from the gateway middleware.
    """

    def ValidateSession(self, request, context):
        """Validate an existing session. Called by gateway on every authenticated request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Create a new session after successful authentication.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateSession(self, request, context):
        """Invalidate a session (logout).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthStatus(self, request, context):
        """Get the current user's authentication status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CredentialVerified(self, request, context):
        """Notify that a credential-based login has been verified (OID4VP callback).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSession,
                    request_deserializer=auth__service__pb2.ValidateSessionRequest.FromString,
                    response_serializer=auth__service__pb2.ValidateSessionResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=auth__service__pb2.CreateSessionRequest.FromString,
                    response_serializer=auth__service__pb2.CreateSessionResponse.SerializeToString,
            ),
            'InvalidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateSession,
                    request_deserializer=auth__service__pb2.InvalidateSessionRequest.FromString,
                    response_serializer=auth__service__pb2.InvalidateSessionResponse.SerializeToString,
            ),
            'GetAuthStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthStatus,
                    request_deserializer=auth__service__pb2.GetAuthStatusRequest.FromString,
                    response_serializer=auth__service__pb2.AuthStatusResponse.SerializeToString,
            ),
            'CredentialVerified': grpc.unary_unary_rpc_method_handler(
                    servicer.CredentialVerified,
                    request_deserializer=auth__service__pb2.CredentialVerifiedRequest.FromString,
                    response_serializer=auth__service__pb2.CredentialVerifiedResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=auth__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=auth__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """AuthService handles session management and user authentication state.
    This is the hottest internal service — called on every authenticated request
    from the gateway middleware.
    """

    @staticmethod
    def ValidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.auth.v1.AuthService/ValidateSession',
            auth__service__pb2.ValidateSessionRequest.SerializeToString,
            auth__service__pb2.ValidateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.auth.v1.AuthService/CreateSession',
            auth__service__pb2.CreateSessionRequest.SerializeToString,
            auth__service__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.auth.v1.AuthService/InvalidateSession',
            auth__service__pb2.InvalidateSessionRequest.SerializeToString,
            auth__service__pb2.InvalidateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.auth.v1.AuthService/GetAuthStatus',
            auth__service__pb2.GetAuthStatusRequest.SerializeToString,
            auth__service__pb2.AuthStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CredentialVerified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.auth.v1.AuthService/CredentialVerified',
            auth__service__pb2.CredentialVerifiedRequest.SerializeToString,
            auth__service__pb2.CredentialVerifiedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.auth.v1.AuthService/HealthCheck',
            auth__service__pb2.HealthCheckRequest.SerializeToString,
            auth__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
