# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import credential_template_service_pb2 as credential__template__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credential_template_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CredentialTemplateServiceStub(object):
    """CredentialTemplateService manages credential template definitions — the
    schemas that drive OID4VCI issuance flows.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTemplate = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/CreateTemplate',
                request_serializer=credential__template__service__pb2.CreateTemplateRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.TemplateResponse.FromString,
                _registered_method=True)
        self.GetTemplate = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/GetTemplate',
                request_serializer=credential__template__service__pb2.GetTemplateRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.TemplateResponse.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/ListTemplates',
                request_serializer=credential__template__service__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.UpdateTemplate = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/UpdateTemplate',
                request_serializer=credential__template__service__pb2.UpdateTemplateRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.TemplateResponse.FromString,
                _registered_method=True)
        self.ActivateTemplate = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/ActivateTemplate',
                request_serializer=credential__template__service__pb2.ActivateTemplateRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.TemplateResponse.FromString,
                _registered_method=True)
        self.DeprecateTemplate = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/DeprecateTemplate',
                request_serializer=credential__template__service__pb2.DeprecateTemplateRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.TemplateResponse.FromString,
                _registered_method=True)
        self.NewVersion = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/NewVersion',
                request_serializer=credential__template__service__pb2.NewVersionRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.TemplateResponse.FromString,
                _registered_method=True)
        self.DeleteTemplate = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/DeleteTemplate',
                request_serializer=credential__template__service__pb2.DeleteTemplateRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.DeleteTemplateResponse.FromString,
                _registered_method=True)
        self.GetCredentialConfigurations = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/GetCredentialConfigurations',
                request_serializer=credential__template__service__pb2.GetCredentialConfigurationsRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.GetCredentialConfigurationsResponse.FromString,
                _registered_method=True)
        self.ListWallets = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/ListWallets',
                request_serializer=credential__template__service__pb2.ListWalletsRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.ListWalletsResponse.FromString,
                _registered_method=True)
        self.GetWallet = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/GetWallet',
                request_serializer=credential__template__service__pb2.GetWalletRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.WalletRegistryEntry.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.credential_template.v1.CredentialTemplateService/HealthCheck',
                request_serializer=credential__template__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=credential__template__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class CredentialTemplateServiceServicer(object):
    """CredentialTemplateService manages credential template definitions — the
    schemas that drive OID4VCI issuance flows.
    """

    def CreateTemplate(self, request, context):
        """Create a new credential template (draft).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTemplate(self, request, context):
        """Get a credential template by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """List credential templates for an organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTemplate(self, request, context):
        """Update a draft credential template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateTemplate(self, request, context):
        """Activate a draft template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeprecateTemplate(self, request, context):
        """Deprecate an active template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewVersion(self, request, context):
        """Create a new version from an existing template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTemplate(self, request, context):
        """Delete a draft template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredentialConfigurations(self, request, context):
        """Get credential configurations for OID4VCI metadata (internal).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWallets(self, request, context):
        """List wallet registry entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallet(self, request, context):
        """Get a wallet registry entry by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredentialTemplateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTemplate,
                    request_deserializer=credential__template__service__pb2.CreateTemplateRequest.FromString,
                    response_serializer=credential__template__service__pb2.TemplateResponse.SerializeToString,
            ),
            'GetTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTemplate,
                    request_deserializer=credential__template__service__pb2.GetTemplateRequest.FromString,
                    response_serializer=credential__template__service__pb2.TemplateResponse.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=credential__template__service__pb2.ListTemplatesRequest.FromString,
                    response_serializer=credential__template__service__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'UpdateTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTemplate,
                    request_deserializer=credential__template__service__pb2.UpdateTemplateRequest.FromString,
                    response_serializer=credential__template__service__pb2.TemplateResponse.SerializeToString,
            ),
            'ActivateTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateTemplate,
                    request_deserializer=credential__template__service__pb2.ActivateTemplateRequest.FromString,
                    response_serializer=credential__template__service__pb2.TemplateResponse.SerializeToString,
            ),
            'DeprecateTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeprecateTemplate,
                    request_deserializer=credential__template__service__pb2.DeprecateTemplateRequest.FromString,
                    response_serializer=credential__template__service__pb2.TemplateResponse.SerializeToString,
            ),
            'NewVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.NewVersion,
                    request_deserializer=credential__template__service__pb2.NewVersionRequest.FromString,
                    response_serializer=credential__template__service__pb2.TemplateResponse.SerializeToString,
            ),
            'DeleteTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTemplate,
                    request_deserializer=credential__template__service__pb2.DeleteTemplateRequest.FromString,
                    response_serializer=credential__template__service__pb2.DeleteTemplateResponse.SerializeToString,
            ),
            'GetCredentialConfigurations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentialConfigurations,
                    request_deserializer=credential__template__service__pb2.GetCredentialConfigurationsRequest.FromString,
                    response_serializer=credential__template__service__pb2.GetCredentialConfigurationsResponse.SerializeToString,
            ),
            'ListWallets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWallets,
                    request_deserializer=credential__template__service__pb2.ListWalletsRequest.FromString,
                    response_serializer=credential__template__service__pb2.ListWalletsResponse.SerializeToString,
            ),
            'GetWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallet,
                    request_deserializer=credential__template__service__pb2.GetWalletRequest.FromString,
                    response_serializer=credential__template__service__pb2.WalletRegistryEntry.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=credential__template__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=credential__template__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.credential_template.v1.CredentialTemplateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.credential_template.v1.CredentialTemplateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CredentialTemplateService(object):
    """CredentialTemplateService manages credential template definitions — the
    schemas that drive OID4VCI issuance flows.
    """

    @staticmethod
    def CreateTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/CreateTemplate',
            credential__template__service__pb2.CreateTemplateRequest.SerializeToString,
            credential__template__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/GetTemplate',
            credential__template__service__pb2.GetTemplateRequest.SerializeToString,
            credential__template__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/ListTemplates',
            credential__template__service__pb2.ListTemplatesRequest.SerializeToString,
            credential__template__service__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/UpdateTemplate',
            credential__template__service__pb2.UpdateTemplateRequest.SerializeToString,
            credential__template__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/ActivateTemplate',
            credential__template__service__pb2.ActivateTemplateRequest.SerializeToString,
            credential__template__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeprecateTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/DeprecateTemplate',
            credential__template__service__pb2.DeprecateTemplateRequest.SerializeToString,
            credential__template__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/NewVersion',
            credential__template__service__pb2.NewVersionRequest.SerializeToString,
            credential__template__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/DeleteTemplate',
            credential__template__service__pb2.DeleteTemplateRequest.SerializeToString,
            credential__template__service__pb2.DeleteTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredentialConfigurations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/GetCredentialConfigurations',
            credential__template__service__pb2.GetCredentialConfigurationsRequest.SerializeToString,
            credential__template__service__pb2.GetCredentialConfigurationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWallets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/ListWallets',
            credential__template__service__pb2.ListWalletsRequest.SerializeToString,
            credential__template__service__pb2.ListWalletsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/GetWallet',
            credential__template__service__pb2.GetWalletRequest.SerializeToString,
            credential__template__service__pb2.WalletRegistryEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.credential_template.v1.CredentialTemplateService/HealthCheck',
            credential__template__service__pb2.HealthCheckRequest.SerializeToString,
            credential__template__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
