# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_stream_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event_stream_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65vent_stream_service.proto\x12\x18marty.ui.event_stream.v1\x1a\x1cgoogle/api/annotations.proto\"p\n\x11\x45ventSubscription\x12\x13\n\x0b\x65vent_types\x18\x01 \x03(\t\x12\x17\n\x0forganization_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61ggregate_type\x18\x03 \x01(\t\x12\x15\n\rsubscriber_id\x18\x04 \x01(\t\"\x91\x02\n\x0b\x44omainEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x14\n\x0c\x61ggregate_id\x18\x03 \x01(\t\x12\x16\n\x0e\x61ggregate_type\x18\x04 \x01(\t\x12\x17\n\x0forganization_id\x18\x05 \x01(\t\x12=\n\x04\x64\x61ta\x18\x06 \x03(\x0b\x32/.marty.ui.event_stream.v1.DomainEvent.DataEntry\x12\x11\n\ttimestamp\x18\x07 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x08 \x01(\t\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\x13PublishEventRequest\x12\x34\n\x05\x65vent\x18\x01 \x01(\x0b\x32%.marty.ui.event_stream.v1.DomainEvent\"E\n\x14PublishEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x14subscribers_notified\x18\x02 \x01(\x05\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8b\x03\n\x12\x45ventStreamService\x12\x63\n\tSubscribe\x12+.marty.ui.event_stream.v1.EventSubscription\x1a%.marty.ui.event_stream.v1.DomainEvent\"\x00\x30\x01\x12\x87\x01\n\x07Publish\x12-.marty.ui.event_stream.v1.PublishEventRequest\x1a..marty.ui.event_stream.v1.PublishEventResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/v1/events/publish:\x01*\x12\x85\x01\n\x0bHealthCheck\x12,.marty.ui.event_stream.v1.HealthCheckRequest\x1a-.marty.ui.event_stream.v1.HealthCheckResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/events/healthB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_stream_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_DOMAINEVENT_DATAENTRY']._loaded_options = None
  _globals['_DOMAINEVENT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_EVENTSTREAMSERVICE'].methods_by_name['Publish']._loaded_options = None
  _globals['_EVENTSTREAMSERVICE'].methods_by_name['Publish']._serialized_options = b'\202\323\344\223\002\027\"\022/v1/events/publish:\001*'
  _globals['_EVENTSTREAMSERVICE'].methods_by_name['HealthCheck']._loaded_options = None
  _globals['_EVENTSTREAMSERVICE'].methods_by_name['HealthCheck']._serialized_options = b'\202\323\344\223\002\023\022\021/v1/events/health'
  _globals['_EVENTSUBSCRIPTION']._serialized_start=86
  _globals['_EVENTSUBSCRIPTION']._serialized_end=198
  _globals['_DOMAINEVENT']._serialized_start=201
  _globals['_DOMAINEVENT']._serialized_end=474
  _globals['_DOMAINEVENT_DATAENTRY']._serialized_start=431
  _globals['_DOMAINEVENT_DATAENTRY']._serialized_end=474
  _globals['_PUBLISHEVENTREQUEST']._serialized_start=476
  _globals['_PUBLISHEVENTREQUEST']._serialized_end=551
  _globals['_PUBLISHEVENTRESPONSE']._serialized_start=553
  _globals['_PUBLISHEVENTRESPONSE']._serialized_end=622
  _globals['_HEALTHCHECKREQUEST']._serialized_start=624
  _globals['_HEALTHCHECKREQUEST']._serialized_end=644
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=646
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=683
  _globals['_EVENTSTREAMSERVICE']._serialized_start=686
  _globals['_EVENTSTREAMSERVICE']._serialized_end=1081
# @@protoc_insertion_point(module_scope)
