# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import event_stream_service_pb2 as event__stream__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in event_stream_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventStreamServiceStub(object):
    """EventStreamService provides a centralized event bus for inter-service
    communication, replacing RabbitMQ publish/subscribe patterns with
    gRPC server streaming.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/marty.ui.event_stream.v1.EventStreamService/Subscribe',
                request_serializer=event__stream__service__pb2.EventSubscription.SerializeToString,
                response_deserializer=event__stream__service__pb2.DomainEvent.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/marty.ui.event_stream.v1.EventStreamService/Publish',
                request_serializer=event__stream__service__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=event__stream__service__pb2.PublishEventResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.event_stream.v1.EventStreamService/HealthCheck',
                request_serializer=event__stream__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=event__stream__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class EventStreamServiceServicer(object):
    """EventStreamService provides a centralized event bus for inter-service
    communication, replacing RabbitMQ publish/subscribe patterns with
    gRPC server streaming.
    """

    def Subscribe(self, request, context):
        """Subscribe to a filtered stream of domain events.
        The server pushes events matching the filter criteria as they occur.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Publish a domain event to all active subscribers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=event__stream__service__pb2.EventSubscription.FromString,
                    response_serializer=event__stream__service__pb2.DomainEvent.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=event__stream__service__pb2.PublishEventRequest.FromString,
                    response_serializer=event__stream__service__pb2.PublishEventResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=event__stream__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=event__stream__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.event_stream.v1.EventStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.event_stream.v1.EventStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventStreamService(object):
    """EventStreamService provides a centralized event bus for inter-service
    communication, replacing RabbitMQ publish/subscribe patterns with
    gRPC server streaming.
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marty.ui.event_stream.v1.EventStreamService/Subscribe',
            event__stream__service__pb2.EventSubscription.SerializeToString,
            event__stream__service__pb2.DomainEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.event_stream.v1.EventStreamService/Publish',
            event__stream__service__pb2.PublishEventRequest.SerializeToString,
            event__stream__service__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.event_stream.v1.EventStreamService/HealthCheck',
            event__stream__service__pb2.HealthCheckRequest.SerializeToString,
            event__stream__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
