# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import flow_service_pb2 as flow__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flow_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlowServiceStub(object):
    """FlowService orchestrates multi-step credential issuance and verification
    workflows including OID4VCI and OID4VP flows.
    -- Flow Definitions --
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFlowDefinition = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/CreateFlowDefinition',
                request_serializer=flow__service__pb2.CreateFlowDefinitionRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowDefinitionResponse.FromString,
                _registered_method=True)
        self.GetFlowDefinition = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/GetFlowDefinition',
                request_serializer=flow__service__pb2.GetFlowDefinitionRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowDefinitionResponse.FromString,
                _registered_method=True)
        self.ListFlowDefinitions = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/ListFlowDefinitions',
                request_serializer=flow__service__pb2.ListFlowDefinitionsRequest.SerializeToString,
                response_deserializer=flow__service__pb2.ListFlowDefinitionsResponse.FromString,
                _registered_method=True)
        self.ActivateFlowDefinition = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/ActivateFlowDefinition',
                request_serializer=flow__service__pb2.ActivateFlowDefinitionRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowDefinitionResponse.FromString,
                _registered_method=True)
        self.DeleteFlowDefinition = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/DeleteFlowDefinition',
                request_serializer=flow__service__pb2.DeleteFlowDefinitionRequest.SerializeToString,
                response_deserializer=flow__service__pb2.DeleteFlowDefinitionResponse.FromString,
                _registered_method=True)
        self.StartFlowInstance = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/StartFlowInstance',
                request_serializer=flow__service__pb2.StartFlowRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowInstanceResponse.FromString,
                _registered_method=True)
        self.GetFlowInstance = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/GetFlowInstance',
                request_serializer=flow__service__pb2.GetFlowInstanceRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowInstanceResponse.FromString,
                _registered_method=True)
        self.ListFlowInstances = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/ListFlowInstances',
                request_serializer=flow__service__pb2.ListFlowInstancesRequest.SerializeToString,
                response_deserializer=flow__service__pb2.ListFlowInstancesResponse.FromString,
                _registered_method=True)
        self.AdvanceFlowInstance = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/AdvanceFlowInstance',
                request_serializer=flow__service__pb2.AdvanceFlowRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowInstanceResponse.FromString,
                _registered_method=True)
        self.CancelFlowInstance = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/CancelFlowInstance',
                request_serializer=flow__service__pb2.CancelFlowRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowInstanceResponse.FromString,
                _registered_method=True)
        self.GetFlowResult = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/GetFlowResult',
                request_serializer=flow__service__pb2.GetFlowResultRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowResultResponse.FromString,
                _registered_method=True)
        self.ListFlowArtifacts = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/ListFlowArtifacts',
                request_serializer=flow__service__pb2.ListFlowArtifactsRequest.SerializeToString,
                response_deserializer=flow__service__pb2.ListFlowArtifactsResponse.FromString,
                _registered_method=True)
        self.StartVerification = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/StartVerification',
                request_serializer=flow__service__pb2.StartVerificationRequest.SerializeToString,
                response_deserializer=flow__service__pb2.VerificationRequestResponse.FromString,
                _registered_method=True)
        self.ApplicationApproved = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/ApplicationApproved',
                request_serializer=flow__service__pb2.ApplicationApprovedEvent.SerializeToString,
                response_deserializer=flow__service__pb2.ApplicationApprovedResponse.FromString,
                _registered_method=True)
        self.StreamFlowUpdates = channel.unary_stream(
                '/marty.ui.flow.v1.FlowService/StreamFlowUpdates',
                request_serializer=flow__service__pb2.StreamFlowUpdatesRequest.SerializeToString,
                response_deserializer=flow__service__pb2.FlowInstanceEvent.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.flow.v1.FlowService/HealthCheck',
                request_serializer=flow__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=flow__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class FlowServiceServicer(object):
    """FlowService orchestrates multi-step credential issuance and verification
    workflows including OID4VCI and OID4VP flows.
    -- Flow Definitions --
    """

    def CreateFlowDefinition(self, request, context):
        """Create a new flow definition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlowDefinition(self, request, context):
        """Get a flow definition by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlowDefinitions(self, request, context):
        """List flow definitions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateFlowDefinition(self, request, context):
        """Activate a draft flow definition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFlowDefinition(self, request, context):
        """Delete a draft flow definition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartFlowInstance(self, request, context):
        """-- Flow Instances --

        Start a new flow instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlowInstance(self, request, context):
        """Get a flow instance by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlowInstances(self, request, context):
        """List flow instances.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceFlowInstance(self, request, context):
        """Advance a flow instance to the next step.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelFlowInstance(self, request, context):
        """Cancel a flow instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlowResult(self, request, context):
        """Get OID4VP verification result for a flow instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlowArtifacts(self, request, context):
        """Get OID4VCI artifacts (QR codes) for a flow instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartVerification(self, request, context):
        """-- Verification (OID4VP) --

        Start an OID4VP verification flow.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplicationApproved(self, request, context):
        """-- Webhook --

        Handle application-approved event (triggers OID4VCI flows).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFlowUpdates(self, request, context):
        """-- Streaming --

        Subscribe to real-time updates for a specific flow instance.
        Server pushes step transitions, status changes, and artifacts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFlowDefinition,
                    request_deserializer=flow__service__pb2.CreateFlowDefinitionRequest.FromString,
                    response_serializer=flow__service__pb2.FlowDefinitionResponse.SerializeToString,
            ),
            'GetFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlowDefinition,
                    request_deserializer=flow__service__pb2.GetFlowDefinitionRequest.FromString,
                    response_serializer=flow__service__pb2.FlowDefinitionResponse.SerializeToString,
            ),
            'ListFlowDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFlowDefinitions,
                    request_deserializer=flow__service__pb2.ListFlowDefinitionsRequest.FromString,
                    response_serializer=flow__service__pb2.ListFlowDefinitionsResponse.SerializeToString,
            ),
            'ActivateFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateFlowDefinition,
                    request_deserializer=flow__service__pb2.ActivateFlowDefinitionRequest.FromString,
                    response_serializer=flow__service__pb2.FlowDefinitionResponse.SerializeToString,
            ),
            'DeleteFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFlowDefinition,
                    request_deserializer=flow__service__pb2.DeleteFlowDefinitionRequest.FromString,
                    response_serializer=flow__service__pb2.DeleteFlowDefinitionResponse.SerializeToString,
            ),
            'StartFlowInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.StartFlowInstance,
                    request_deserializer=flow__service__pb2.StartFlowRequest.FromString,
                    response_serializer=flow__service__pb2.FlowInstanceResponse.SerializeToString,
            ),
            'GetFlowInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlowInstance,
                    request_deserializer=flow__service__pb2.GetFlowInstanceRequest.FromString,
                    response_serializer=flow__service__pb2.FlowInstanceResponse.SerializeToString,
            ),
            'ListFlowInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFlowInstances,
                    request_deserializer=flow__service__pb2.ListFlowInstancesRequest.FromString,
                    response_serializer=flow__service__pb2.ListFlowInstancesResponse.SerializeToString,
            ),
            'AdvanceFlowInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceFlowInstance,
                    request_deserializer=flow__service__pb2.AdvanceFlowRequest.FromString,
                    response_serializer=flow__service__pb2.FlowInstanceResponse.SerializeToString,
            ),
            'CancelFlowInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelFlowInstance,
                    request_deserializer=flow__service__pb2.CancelFlowRequest.FromString,
                    response_serializer=flow__service__pb2.FlowInstanceResponse.SerializeToString,
            ),
            'GetFlowResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlowResult,
                    request_deserializer=flow__service__pb2.GetFlowResultRequest.FromString,
                    response_serializer=flow__service__pb2.FlowResultResponse.SerializeToString,
            ),
            'ListFlowArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFlowArtifacts,
                    request_deserializer=flow__service__pb2.ListFlowArtifactsRequest.FromString,
                    response_serializer=flow__service__pb2.ListFlowArtifactsResponse.SerializeToString,
            ),
            'StartVerification': grpc.unary_unary_rpc_method_handler(
                    servicer.StartVerification,
                    request_deserializer=flow__service__pb2.StartVerificationRequest.FromString,
                    response_serializer=flow__service__pb2.VerificationRequestResponse.SerializeToString,
            ),
            'ApplicationApproved': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplicationApproved,
                    request_deserializer=flow__service__pb2.ApplicationApprovedEvent.FromString,
                    response_serializer=flow__service__pb2.ApplicationApprovedResponse.SerializeToString,
            ),
            'StreamFlowUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFlowUpdates,
                    request_deserializer=flow__service__pb2.StreamFlowUpdatesRequest.FromString,
                    response_serializer=flow__service__pb2.FlowInstanceEvent.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=flow__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=flow__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.flow.v1.FlowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.flow.v1.FlowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlowService(object):
    """FlowService orchestrates multi-step credential issuance and verification
    workflows including OID4VCI and OID4VP flows.
    -- Flow Definitions --
    """

    @staticmethod
    def CreateFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/CreateFlowDefinition',
            flow__service__pb2.CreateFlowDefinitionRequest.SerializeToString,
            flow__service__pb2.FlowDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/GetFlowDefinition',
            flow__service__pb2.GetFlowDefinitionRequest.SerializeToString,
            flow__service__pb2.FlowDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFlowDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/ListFlowDefinitions',
            flow__service__pb2.ListFlowDefinitionsRequest.SerializeToString,
            flow__service__pb2.ListFlowDefinitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/ActivateFlowDefinition',
            flow__service__pb2.ActivateFlowDefinitionRequest.SerializeToString,
            flow__service__pb2.FlowDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/DeleteFlowDefinition',
            flow__service__pb2.DeleteFlowDefinitionRequest.SerializeToString,
            flow__service__pb2.DeleteFlowDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartFlowInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/StartFlowInstance',
            flow__service__pb2.StartFlowRequest.SerializeToString,
            flow__service__pb2.FlowInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlowInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/GetFlowInstance',
            flow__service__pb2.GetFlowInstanceRequest.SerializeToString,
            flow__service__pb2.FlowInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFlowInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/ListFlowInstances',
            flow__service__pb2.ListFlowInstancesRequest.SerializeToString,
            flow__service__pb2.ListFlowInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceFlowInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/AdvanceFlowInstance',
            flow__service__pb2.AdvanceFlowRequest.SerializeToString,
            flow__service__pb2.FlowInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelFlowInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/CancelFlowInstance',
            flow__service__pb2.CancelFlowRequest.SerializeToString,
            flow__service__pb2.FlowInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlowResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/GetFlowResult',
            flow__service__pb2.GetFlowResultRequest.SerializeToString,
            flow__service__pb2.FlowResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFlowArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/ListFlowArtifacts',
            flow__service__pb2.ListFlowArtifactsRequest.SerializeToString,
            flow__service__pb2.ListFlowArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartVerification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/StartVerification',
            flow__service__pb2.StartVerificationRequest.SerializeToString,
            flow__service__pb2.VerificationRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplicationApproved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/ApplicationApproved',
            flow__service__pb2.ApplicationApprovedEvent.SerializeToString,
            flow__service__pb2.ApplicationApprovedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFlowUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/StreamFlowUpdates',
            flow__service__pb2.StreamFlowUpdatesRequest.SerializeToString,
            flow__service__pb2.FlowInstanceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.flow.v1.FlowService/HealthCheck',
            flow__service__pb2.HealthCheckRequest.SerializeToString,
            flow__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
