# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import issuance_service_pb2 as issuance__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in issuance_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IssuanceServiceStub(object):
    """IssuanceService handles OID4VCI credential issuance, lifecycle management,
    and application processing.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateIssuance = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/InitiateIssuance',
                request_serializer=issuance__service__pb2.InitiateIssuanceRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.IssuanceResponse.FromString,
                _registered_method=True)
        self.ExchangeToken = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/ExchangeToken',
                request_serializer=issuance__service__pb2.ExchangeTokenRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.IssueCredential = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/IssueCredential',
                request_serializer=issuance__service__pb2.IssueCredentialRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.IssueCredentialResponse.FromString,
                _registered_method=True)
        self.GetOffer = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/GetOffer',
                request_serializer=issuance__service__pb2.GetOfferRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.OfferResponse.FromString,
                _registered_method=True)
        self.ListTransactions = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/ListTransactions',
                request_serializer=issuance__service__pb2.ListTransactionsRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.ListTransactionsResponse.FromString,
                _registered_method=True)
        self.GetTransaction = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/GetTransaction',
                request_serializer=issuance__service__pb2.GetTransactionRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.RevokeCredential = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/RevokeCredential',
                request_serializer=issuance__service__pb2.CredentialLifecycleRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.CredentialStatusResponse.FromString,
                _registered_method=True)
        self.SuspendCredential = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/SuspendCredential',
                request_serializer=issuance__service__pb2.CredentialLifecycleRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.CredentialStatusResponse.FromString,
                _registered_method=True)
        self.ReinstateCredential = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/ReinstateCredential',
                request_serializer=issuance__service__pb2.CredentialLifecycleRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.CredentialStatusResponse.FromString,
                _registered_method=True)
        self.GetCredentialStatus = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/GetCredentialStatus',
                request_serializer=issuance__service__pb2.GetCredentialStatusRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.CredentialStatusResponse.FromString,
                _registered_method=True)
        self.StreamCredentialEvents = channel.unary_stream(
                '/marty.ui.issuance.v1.IssuanceService/StreamCredentialEvents',
                request_serializer=issuance__service__pb2.StreamCredentialEventsRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.CredentialEvent.FromString,
                _registered_method=True)
        self.DidcommDeliver = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/DidcommDeliver',
                request_serializer=issuance__service__pb2.DidcommDeliverRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.DidcommDeliverResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.issuance.v1.IssuanceService/HealthCheck',
                request_serializer=issuance__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=issuance__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class IssuanceServiceServicer(object):
    """IssuanceService handles OID4VCI credential issuance, lifecycle management,
    and application processing.
    """

    def InitiateIssuance(self, request, context):
        """Initiate a credential offer (returns credential_offer_uri for QR code).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeToken(self, request, context):
        """Exchange a pre-authorized code or authorization code for an access token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueCredential(self, request, context):
        """Issue a credential (requires valid access token and proof JWT).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOffer(self, request, context):
        """Get a credential offer by transaction ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTransactions(self, request, context):
        """List issuance transactions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
        """Get a single issuance transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCredential(self, request, context):
        """Revoke a credential.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendCredential(self, request, context):
        """Suspend a credential.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReinstateCredential(self, request, context):
        """Reinstate a suspended credential.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredentialStatus(self, request, context):
        """Get credential status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCredentialEvents(self, request, context):
        """-- Streaming --

        Subscribe to real-time credential lifecycle events.
        Server pushes issuance, revocation, suspension, and reinstatement events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DidcommDeliver(self, request, context):
        """Deliver a credential via DIDComm v2 push.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IssuanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateIssuance': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateIssuance,
                    request_deserializer=issuance__service__pb2.InitiateIssuanceRequest.FromString,
                    response_serializer=issuance__service__pb2.IssuanceResponse.SerializeToString,
            ),
            'ExchangeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeToken,
                    request_deserializer=issuance__service__pb2.ExchangeTokenRequest.FromString,
                    response_serializer=issuance__service__pb2.TokenResponse.SerializeToString,
            ),
            'IssueCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueCredential,
                    request_deserializer=issuance__service__pb2.IssueCredentialRequest.FromString,
                    response_serializer=issuance__service__pb2.IssueCredentialResponse.SerializeToString,
            ),
            'GetOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOffer,
                    request_deserializer=issuance__service__pb2.GetOfferRequest.FromString,
                    response_serializer=issuance__service__pb2.OfferResponse.SerializeToString,
            ),
            'ListTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTransactions,
                    request_deserializer=issuance__service__pb2.ListTransactionsRequest.FromString,
                    response_serializer=issuance__service__pb2.ListTransactionsResponse.SerializeToString,
            ),
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=issuance__service__pb2.GetTransactionRequest.FromString,
                    response_serializer=issuance__service__pb2.TransactionResponse.SerializeToString,
            ),
            'RevokeCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCredential,
                    request_deserializer=issuance__service__pb2.CredentialLifecycleRequest.FromString,
                    response_serializer=issuance__service__pb2.CredentialStatusResponse.SerializeToString,
            ),
            'SuspendCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendCredential,
                    request_deserializer=issuance__service__pb2.CredentialLifecycleRequest.FromString,
                    response_serializer=issuance__service__pb2.CredentialStatusResponse.SerializeToString,
            ),
            'ReinstateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.ReinstateCredential,
                    request_deserializer=issuance__service__pb2.CredentialLifecycleRequest.FromString,
                    response_serializer=issuance__service__pb2.CredentialStatusResponse.SerializeToString,
            ),
            'GetCredentialStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentialStatus,
                    request_deserializer=issuance__service__pb2.GetCredentialStatusRequest.FromString,
                    response_serializer=issuance__service__pb2.CredentialStatusResponse.SerializeToString,
            ),
            'StreamCredentialEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCredentialEvents,
                    request_deserializer=issuance__service__pb2.StreamCredentialEventsRequest.FromString,
                    response_serializer=issuance__service__pb2.CredentialEvent.SerializeToString,
            ),
            'DidcommDeliver': grpc.unary_unary_rpc_method_handler(
                    servicer.DidcommDeliver,
                    request_deserializer=issuance__service__pb2.DidcommDeliverRequest.FromString,
                    response_serializer=issuance__service__pb2.DidcommDeliverResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=issuance__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=issuance__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.issuance.v1.IssuanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.issuance.v1.IssuanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IssuanceService(object):
    """IssuanceService handles OID4VCI credential issuance, lifecycle management,
    and application processing.
    """

    @staticmethod
    def InitiateIssuance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/InitiateIssuance',
            issuance__service__pb2.InitiateIssuanceRequest.SerializeToString,
            issuance__service__pb2.IssuanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/ExchangeToken',
            issuance__service__pb2.ExchangeTokenRequest.SerializeToString,
            issuance__service__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/IssueCredential',
            issuance__service__pb2.IssueCredentialRequest.SerializeToString,
            issuance__service__pb2.IssueCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/GetOffer',
            issuance__service__pb2.GetOfferRequest.SerializeToString,
            issuance__service__pb2.OfferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/ListTransactions',
            issuance__service__pb2.ListTransactionsRequest.SerializeToString,
            issuance__service__pb2.ListTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/GetTransaction',
            issuance__service__pb2.GetTransactionRequest.SerializeToString,
            issuance__service__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/RevokeCredential',
            issuance__service__pb2.CredentialLifecycleRequest.SerializeToString,
            issuance__service__pb2.CredentialStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/SuspendCredential',
            issuance__service__pb2.CredentialLifecycleRequest.SerializeToString,
            issuance__service__pb2.CredentialStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReinstateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/ReinstateCredential',
            issuance__service__pb2.CredentialLifecycleRequest.SerializeToString,
            issuance__service__pb2.CredentialStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredentialStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/GetCredentialStatus',
            issuance__service__pb2.GetCredentialStatusRequest.SerializeToString,
            issuance__service__pb2.CredentialStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCredentialEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/StreamCredentialEvents',
            issuance__service__pb2.StreamCredentialEventsRequest.SerializeToString,
            issuance__service__pb2.CredentialEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DidcommDeliver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/DidcommDeliver',
            issuance__service__pb2.DidcommDeliverRequest.SerializeToString,
            issuance__service__pb2.DidcommDeliverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.issuance.v1.IssuanceService/HealthCheck',
            issuance__service__pb2.HealthCheckRequest.SerializeToString,
            issuance__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
