# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import organization_service_pb2 as organization__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in organization_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrganizationServiceStub(object):
    """OrganizationService handles organization management, membership, and API key
    validation. The internal RPCs (GetMember, ValidateApiKey) are called by every
    service for authorization checks.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrganization = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/GetOrganization',
                request_serializer=organization__service__pb2.GetOrganizationRequest.SerializeToString,
                response_deserializer=organization__service__pb2.OrganizationResponse.FromString,
                _registered_method=True)
        self.CreateOrganization = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/CreateOrganization',
                request_serializer=organization__service__pb2.CreateOrganizationRequest.SerializeToString,
                response_deserializer=organization__service__pb2.OrganizationResponse.FromString,
                _registered_method=True)
        self.UpdateOrganization = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/UpdateOrganization',
                request_serializer=organization__service__pb2.UpdateOrganizationRequest.SerializeToString,
                response_deserializer=organization__service__pb2.OrganizationResponse.FromString,
                _registered_method=True)
        self.ListOrganizations = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/ListOrganizations',
                request_serializer=organization__service__pb2.ListOrganizationsRequest.SerializeToString,
                response_deserializer=organization__service__pb2.ListOrganizationsResponse.FromString,
                _registered_method=True)
        self.GetMember = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/GetMember',
                request_serializer=organization__service__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=organization__service__pb2.MemberResponse.FromString,
                _registered_method=True)
        self.AddMember = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/AddMember',
                request_serializer=organization__service__pb2.AddMemberRequest.SerializeToString,
                response_deserializer=organization__service__pb2.MemberResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/UpdateMember',
                request_serializer=organization__service__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=organization__service__pb2.MemberResponse.FromString,
                _registered_method=True)
        self.RemoveMember = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/RemoveMember',
                request_serializer=organization__service__pb2.RemoveMemberRequest.SerializeToString,
                response_deserializer=organization__service__pb2.RemoveMemberResponse.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/ListMembers',
                request_serializer=organization__service__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=organization__service__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.ValidateApiKey = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/ValidateApiKey',
                request_serializer=organization__service__pb2.ValidateApiKeyRequest.SerializeToString,
                response_deserializer=organization__service__pb2.ValidateApiKeyResponse.FromString,
                _registered_method=True)
        self.GetMemberPermissions = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/GetMemberPermissions',
                request_serializer=organization__service__pb2.GetMemberPermissionsRequest.SerializeToString,
                response_deserializer=organization__service__pb2.GetMemberPermissionsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.organization.v1.OrganizationService/HealthCheck',
                request_serializer=organization__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=organization__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class OrganizationServiceServicer(object):
    """OrganizationService handles organization management, membership, and API key
    validation. The internal RPCs (GetMember, ValidateApiKey) are called by every
    service for authorization checks.
    """

    def GetOrganization(self, request, context):
        """Get an organization by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganization(self, request, context):
        """Create a new organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrganization(self, request, context):
        """Update an organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """List organizations (with optional filters).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMember(self, request, context):
        """Get a member within an organization (internal — used for auth checks).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMember(self, request, context):
        """Add a member to an organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Update a member's role.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMember(self, request, context):
        """Remove a member from an organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """List members of an organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateApiKey(self, request, context):
        """Validate an API key (internal — used for API key auth).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemberPermissions(self, request, context):
        """Get member permissions (flattened).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrganizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=organization__service__pb2.GetOrganizationRequest.FromString,
                    response_serializer=organization__service__pb2.OrganizationResponse.SerializeToString,
            ),
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=organization__service__pb2.CreateOrganizationRequest.FromString,
                    response_serializer=organization__service__pb2.OrganizationResponse.SerializeToString,
            ),
            'UpdateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrganization,
                    request_deserializer=organization__service__pb2.UpdateOrganizationRequest.FromString,
                    response_serializer=organization__service__pb2.OrganizationResponse.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=organization__service__pb2.ListOrganizationsRequest.FromString,
                    response_serializer=organization__service__pb2.ListOrganizationsResponse.SerializeToString,
            ),
            'GetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMember,
                    request_deserializer=organization__service__pb2.GetMemberRequest.FromString,
                    response_serializer=organization__service__pb2.MemberResponse.SerializeToString,
            ),
            'AddMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMember,
                    request_deserializer=organization__service__pb2.AddMemberRequest.FromString,
                    response_serializer=organization__service__pb2.MemberResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=organization__service__pb2.UpdateMemberRequest.FromString,
                    response_serializer=organization__service__pb2.MemberResponse.SerializeToString,
            ),
            'RemoveMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMember,
                    request_deserializer=organization__service__pb2.RemoveMemberRequest.FromString,
                    response_serializer=organization__service__pb2.RemoveMemberResponse.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=organization__service__pb2.ListMembersRequest.FromString,
                    response_serializer=organization__service__pb2.ListMembersResponse.SerializeToString,
            ),
            'ValidateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateApiKey,
                    request_deserializer=organization__service__pb2.ValidateApiKeyRequest.FromString,
                    response_serializer=organization__service__pb2.ValidateApiKeyResponse.SerializeToString,
            ),
            'GetMemberPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemberPermissions,
                    request_deserializer=organization__service__pb2.GetMemberPermissionsRequest.FromString,
                    response_serializer=organization__service__pb2.GetMemberPermissionsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=organization__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=organization__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.organization.v1.OrganizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.organization.v1.OrganizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrganizationService(object):
    """OrganizationService handles organization management, membership, and API key
    validation. The internal RPCs (GetMember, ValidateApiKey) are called by every
    service for authorization checks.
    """

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/GetOrganization',
            organization__service__pb2.GetOrganizationRequest.SerializeToString,
            organization__service__pb2.OrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/CreateOrganization',
            organization__service__pb2.CreateOrganizationRequest.SerializeToString,
            organization__service__pb2.OrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/UpdateOrganization',
            organization__service__pb2.UpdateOrganizationRequest.SerializeToString,
            organization__service__pb2.OrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/ListOrganizations',
            organization__service__pb2.ListOrganizationsRequest.SerializeToString,
            organization__service__pb2.ListOrganizationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/GetMember',
            organization__service__pb2.GetMemberRequest.SerializeToString,
            organization__service__pb2.MemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/AddMember',
            organization__service__pb2.AddMemberRequest.SerializeToString,
            organization__service__pb2.MemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/UpdateMember',
            organization__service__pb2.UpdateMemberRequest.SerializeToString,
            organization__service__pb2.MemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/RemoveMember',
            organization__service__pb2.RemoveMemberRequest.SerializeToString,
            organization__service__pb2.RemoveMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/ListMembers',
            organization__service__pb2.ListMembersRequest.SerializeToString,
            organization__service__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/ValidateApiKey',
            organization__service__pb2.ValidateApiKeyRequest.SerializeToString,
            organization__service__pb2.ValidateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemberPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/GetMemberPermissions',
            organization__service__pb2.GetMemberPermissionsRequest.SerializeToString,
            organization__service__pb2.GetMemberPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.organization.v1.OrganizationService/HealthCheck',
            organization__service__pb2.HealthCheckRequest.SerializeToString,
            organization__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
