# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import presentation_policy_service_pb2 as presentation__policy__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in presentation_policy_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresentationPolicyServiceStub(object):
    """---------------------------------------------------------------------------
    Presentation Policy Service — manages OID4VP presentation policies and
    evaluates verifiable presentations against those policies.

    Used by the flow service to:
    1. Look up a policy (GetPolicy) to resolve org ownership / build
    presentation definitions.
    2. Evaluate a submitted VP token (EvaluatePresentation) post-submission.
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPolicy = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/GetPolicy',
                request_serializer=presentation__policy__service__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/ListPolicies',
                request_serializer=presentation__policy__service__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/CreatePolicy',
                request_serializer=presentation__policy__service__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/UpdatePolicy',
                request_serializer=presentation__policy__service__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.ActivatePolicy = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/ActivatePolicy',
                request_serializer=presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.SuspendPolicy = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/SuspendPolicy',
                request_serializer=presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.NewVersionPolicy = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/NewVersionPolicy',
                request_serializer=presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/DeletePolicy',
                request_serializer=presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.DeletePolicyResponse.FromString,
                _registered_method=True)
        self.EvaluatePresentation = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/EvaluatePresentation',
                request_serializer=presentation__policy__service__pb2.EvaluatePresentationRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.PolicyEvaluationResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.presentation_policy.v1.PresentationPolicyService/HealthCheck',
                request_serializer=presentation__policy__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=presentation__policy__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PresentationPolicyServiceServicer(object):
    """---------------------------------------------------------------------------
    Presentation Policy Service — manages OID4VP presentation policies and
    evaluates verifiable presentations against those policies.

    Used by the flow service to:
    1. Look up a policy (GetPolicy) to resolve org ownership / build
    presentation definitions.
    2. Evaluate a submitted VP token (EvaluatePresentation) post-submission.
    ---------------------------------------------------------------------------

    """

    def GetPolicy(self, request, context):
        """Retrieve a single presentation policy by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """List policies (optionally filtered by organization).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Create a new presentation policy (draft).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Update mutable fields of a draft policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivatePolicy(self, request, context):
        """Activate a draft or suspended policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendPolicy(self, request, context):
        """Suspend an active policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewVersionPolicy(self, request, context):
        """Create a new draft version from an existing policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Delete a draft policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePresentation(self, request, context):
        """Evaluate a verifiable presentation against a stored policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresentationPolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=presentation__policy__service__pb2.GetPolicyRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.PolicyResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=presentation__policy__service__pb2.ListPoliciesRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=presentation__policy__service__pb2.CreatePolicyRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.PolicyResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=presentation__policy__service__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.PolicyResponse.SerializeToString,
            ),
            'ActivatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivatePolicy,
                    request_deserializer=presentation__policy__service__pb2.PolicyIdRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.PolicyResponse.SerializeToString,
            ),
            'SuspendPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendPolicy,
                    request_deserializer=presentation__policy__service__pb2.PolicyIdRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.PolicyResponse.SerializeToString,
            ),
            'NewVersionPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.NewVersionPolicy,
                    request_deserializer=presentation__policy__service__pb2.PolicyIdRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.PolicyResponse.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=presentation__policy__service__pb2.PolicyIdRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.DeletePolicyResponse.SerializeToString,
            ),
            'EvaluatePresentation': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePresentation,
                    request_deserializer=presentation__policy__service__pb2.EvaluatePresentationRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.PolicyEvaluationResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=presentation__policy__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=presentation__policy__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.presentation_policy.v1.PresentationPolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.presentation_policy.v1.PresentationPolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresentationPolicyService(object):
    """---------------------------------------------------------------------------
    Presentation Policy Service — manages OID4VP presentation policies and
    evaluates verifiable presentations against those policies.

    Used by the flow service to:
    1. Look up a policy (GetPolicy) to resolve org ownership / build
    presentation definitions.
    2. Evaluate a submitted VP token (EvaluatePresentation) post-submission.
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/GetPolicy',
            presentation__policy__service__pb2.GetPolicyRequest.SerializeToString,
            presentation__policy__service__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/ListPolicies',
            presentation__policy__service__pb2.ListPoliciesRequest.SerializeToString,
            presentation__policy__service__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/CreatePolicy',
            presentation__policy__service__pb2.CreatePolicyRequest.SerializeToString,
            presentation__policy__service__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/UpdatePolicy',
            presentation__policy__service__pb2.UpdatePolicyRequest.SerializeToString,
            presentation__policy__service__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/ActivatePolicy',
            presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
            presentation__policy__service__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/SuspendPolicy',
            presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
            presentation__policy__service__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewVersionPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/NewVersionPolicy',
            presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
            presentation__policy__service__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/DeletePolicy',
            presentation__policy__service__pb2.PolicyIdRequest.SerializeToString,
            presentation__policy__service__pb2.DeletePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePresentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/EvaluatePresentation',
            presentation__policy__service__pb2.EvaluatePresentationRequest.SerializeToString,
            presentation__policy__service__pb2.PolicyEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.presentation_policy.v1.PresentationPolicyService/HealthCheck',
            presentation__policy__service__pb2.HealthCheckRequest.SerializeToString,
            presentation__policy__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
