# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import revocation_profile_service_pb2 as revocation__profile__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in revocation_profile_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RevocationProfileServiceStub(object):
    """RevocationProfileService manages format-agnostic revocation configuration
    and automation for both issuers (status list publishing) and verifiers
    (revocation checking).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRevocationProfile = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/CreateRevocationProfile',
                request_serializer=revocation__profile__service__pb2.CreateRevocationProfileRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.RevocationProfileResponse.FromString,
                _registered_method=True)
        self.GetRevocationProfile = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/GetRevocationProfile',
                request_serializer=revocation__profile__service__pb2.GetRevocationProfileRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.RevocationProfileResponse.FromString,
                _registered_method=True)
        self.ListRevocationProfiles = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/ListRevocationProfiles',
                request_serializer=revocation__profile__service__pb2.ListRevocationProfilesRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.ListRevocationProfilesResponse.FromString,
                _registered_method=True)
        self.ActivateRevocationProfile = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/ActivateRevocationProfile',
                request_serializer=revocation__profile__service__pb2.ActivateRevocationProfileRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.RevocationProfileResponse.FromString,
                _registered_method=True)
        self.DeleteRevocationProfile = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/DeleteRevocationProfile',
                request_serializer=revocation__profile__service__pb2.DeleteRevocationProfileRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.DeleteRevocationProfileResponse.FromString,
                _registered_method=True)
        self.ProcessRevocation = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/ProcessRevocation',
                request_serializer=revocation__profile__service__pb2.ProcessRevocationRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.ProcessRevocationResponse.FromString,
                _registered_method=True)
        self.AllocateIndex = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/AllocateIndex',
                request_serializer=revocation__profile__service__pb2.AllocateIndexRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.AllocateIndexResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.revocation_profile.v1.RevocationProfileService/HealthCheck',
                request_serializer=revocation__profile__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=revocation__profile__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RevocationProfileServiceServicer(object):
    """RevocationProfileService manages format-agnostic revocation configuration
    and automation for both issuers (status list publishing) and verifiers
    (revocation checking).
    """

    def CreateRevocationProfile(self, request, context):
        """Create a new RevocationProfile (draft).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevocationProfile(self, request, context):
        """Get a RevocationProfile by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRevocationProfiles(self, request, context):
        """List RevocationProfiles for an organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateRevocationProfile(self, request, context):
        """Activate a draft RevocationProfile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRevocationProfile(self, request, context):
        """Delete a RevocationProfile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessRevocation(self, request, context):
        """Process a revocation/suspension/reinstatement (internal, service-to-service).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateIndex(self, request, context):
        """Allocate a status list index for a new credential (internal, service-to-service).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RevocationProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRevocationProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRevocationProfile,
                    request_deserializer=revocation__profile__service__pb2.CreateRevocationProfileRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.RevocationProfileResponse.SerializeToString,
            ),
            'GetRevocationProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevocationProfile,
                    request_deserializer=revocation__profile__service__pb2.GetRevocationProfileRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.RevocationProfileResponse.SerializeToString,
            ),
            'ListRevocationProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRevocationProfiles,
                    request_deserializer=revocation__profile__service__pb2.ListRevocationProfilesRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.ListRevocationProfilesResponse.SerializeToString,
            ),
            'ActivateRevocationProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateRevocationProfile,
                    request_deserializer=revocation__profile__service__pb2.ActivateRevocationProfileRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.RevocationProfileResponse.SerializeToString,
            ),
            'DeleteRevocationProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRevocationProfile,
                    request_deserializer=revocation__profile__service__pb2.DeleteRevocationProfileRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.DeleteRevocationProfileResponse.SerializeToString,
            ),
            'ProcessRevocation': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessRevocation,
                    request_deserializer=revocation__profile__service__pb2.ProcessRevocationRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.ProcessRevocationResponse.SerializeToString,
            ),
            'AllocateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateIndex,
                    request_deserializer=revocation__profile__service__pb2.AllocateIndexRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.AllocateIndexResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=revocation__profile__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=revocation__profile__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.revocation_profile.v1.RevocationProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.revocation_profile.v1.RevocationProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RevocationProfileService(object):
    """RevocationProfileService manages format-agnostic revocation configuration
    and automation for both issuers (status list publishing) and verifiers
    (revocation checking).
    """

    @staticmethod
    def CreateRevocationProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/CreateRevocationProfile',
            revocation__profile__service__pb2.CreateRevocationProfileRequest.SerializeToString,
            revocation__profile__service__pb2.RevocationProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevocationProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/GetRevocationProfile',
            revocation__profile__service__pb2.GetRevocationProfileRequest.SerializeToString,
            revocation__profile__service__pb2.RevocationProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRevocationProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/ListRevocationProfiles',
            revocation__profile__service__pb2.ListRevocationProfilesRequest.SerializeToString,
            revocation__profile__service__pb2.ListRevocationProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateRevocationProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/ActivateRevocationProfile',
            revocation__profile__service__pb2.ActivateRevocationProfileRequest.SerializeToString,
            revocation__profile__service__pb2.RevocationProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRevocationProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/DeleteRevocationProfile',
            revocation__profile__service__pb2.DeleteRevocationProfileRequest.SerializeToString,
            revocation__profile__service__pb2.DeleteRevocationProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessRevocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/ProcessRevocation',
            revocation__profile__service__pb2.ProcessRevocationRequest.SerializeToString,
            revocation__profile__service__pb2.ProcessRevocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/AllocateIndex',
            revocation__profile__service__pb2.AllocateIndexRequest.SerializeToString,
            revocation__profile__service__pb2.AllocateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.revocation_profile.v1.RevocationProfileService/HealthCheck',
            revocation__profile__service__pb2.HealthCheckRequest.SerializeToString,
            revocation__profile__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
