# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import verification_service_pb2 as verification__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verification_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VerificationServiceStub(object):
    """---------------------------------------------------------------------------
    Verification Service — standalone credential verification sessions.

    Manages the full OID4VP presentation exchange lifecycle:
    1. StartVerification  — create a session with request_uri / QR code
    2. GetSession         — poll status
    3. SubmitPresentation — wallet posts VP token
    4. EvaluatePresentation — stateless (no session required)
    5. ListSessions       — audit / analytics
    6. GetInspectionResult — retrieve prior inspection outcome by session
    7. HealthCheck
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartVerification = channel.unary_unary(
                '/marty.ui.verification.v1.VerificationService/StartVerification',
                request_serializer=verification__service__pb2.StartVerificationRequest.SerializeToString,
                response_deserializer=verification__service__pb2.VerificationSession.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/marty.ui.verification.v1.VerificationService/GetSession',
                request_serializer=verification__service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=verification__service__pb2.VerificationSession.FromString,
                _registered_method=True)
        self.SubmitPresentation = channel.unary_unary(
                '/marty.ui.verification.v1.VerificationService/SubmitPresentation',
                request_serializer=verification__service__pb2.SubmitPresentationRequest.SerializeToString,
                response_deserializer=verification__service__pb2.VerificationResult.FromString,
                _registered_method=True)
        self.EvaluatePresentation = channel.unary_unary(
                '/marty.ui.verification.v1.VerificationService/EvaluatePresentation',
                request_serializer=verification__service__pb2.EvaluatePresentationRequest.SerializeToString,
                response_deserializer=verification__service__pb2.VerificationResult.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/marty.ui.verification.v1.VerificationService/ListSessions',
                request_serializer=verification__service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=verification__service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.GetInspectionResult = channel.unary_unary(
                '/marty.ui.verification.v1.VerificationService/GetInspectionResult',
                request_serializer=verification__service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=verification__service__pb2.InspectionResultResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.verification.v1.VerificationService/HealthCheck',
                request_serializer=verification__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=verification__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class VerificationServiceServicer(object):
    """---------------------------------------------------------------------------
    Verification Service — standalone credential verification sessions.

    Manages the full OID4VP presentation exchange lifecycle:
    1. StartVerification  — create a session with request_uri / QR code
    2. GetSession         — poll status
    3. SubmitPresentation — wallet posts VP token
    4. EvaluatePresentation — stateless (no session required)
    5. ListSessions       — audit / analytics
    6. GetInspectionResult — retrieve prior inspection outcome by session
    7. HealthCheck
    ---------------------------------------------------------------------------

    """

    def StartVerification(self, request, context):
        """Create a verification session.  Returns a request_uri for OID4VP wallets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Retrieve session state (polling by relying-party UI).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPresentation(self, request, context):
        """Submit a VP token to a pending session (called by wallet or proxy).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePresentation(self, request, context):
        """Stateless evaluation — no session stored.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List verification sessions for an organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInspectionResult(self, request, context):
        """Retrieve the detailed inspection result for a completed session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartVerification': grpc.unary_unary_rpc_method_handler(
                    servicer.StartVerification,
                    request_deserializer=verification__service__pb2.StartVerificationRequest.FromString,
                    response_serializer=verification__service__pb2.VerificationSession.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=verification__service__pb2.GetSessionRequest.FromString,
                    response_serializer=verification__service__pb2.VerificationSession.SerializeToString,
            ),
            'SubmitPresentation': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPresentation,
                    request_deserializer=verification__service__pb2.SubmitPresentationRequest.FromString,
                    response_serializer=verification__service__pb2.VerificationResult.SerializeToString,
            ),
            'EvaluatePresentation': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePresentation,
                    request_deserializer=verification__service__pb2.EvaluatePresentationRequest.FromString,
                    response_serializer=verification__service__pb2.VerificationResult.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=verification__service__pb2.ListSessionsRequest.FromString,
                    response_serializer=verification__service__pb2.ListSessionsResponse.SerializeToString,
            ),
            'GetInspectionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInspectionResult,
                    request_deserializer=verification__service__pb2.GetSessionRequest.FromString,
                    response_serializer=verification__service__pb2.InspectionResultResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=verification__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=verification__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.verification.v1.VerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.verification.v1.VerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VerificationService(object):
    """---------------------------------------------------------------------------
    Verification Service — standalone credential verification sessions.

    Manages the full OID4VP presentation exchange lifecycle:
    1. StartVerification  — create a session with request_uri / QR code
    2. GetSession         — poll status
    3. SubmitPresentation — wallet posts VP token
    4. EvaluatePresentation — stateless (no session required)
    5. ListSessions       — audit / analytics
    6. GetInspectionResult — retrieve prior inspection outcome by session
    7. HealthCheck
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def StartVerification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.verification.v1.VerificationService/StartVerification',
            verification__service__pb2.StartVerificationRequest.SerializeToString,
            verification__service__pb2.VerificationSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.verification.v1.VerificationService/GetSession',
            verification__service__pb2.GetSessionRequest.SerializeToString,
            verification__service__pb2.VerificationSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPresentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.verification.v1.VerificationService/SubmitPresentation',
            verification__service__pb2.SubmitPresentationRequest.SerializeToString,
            verification__service__pb2.VerificationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePresentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.verification.v1.VerificationService/EvaluatePresentation',
            verification__service__pb2.EvaluatePresentationRequest.SerializeToString,
            verification__service__pb2.VerificationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.verification.v1.VerificationService/ListSessions',
            verification__service__pb2.ListSessionsRequest.SerializeToString,
            verification__service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInspectionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.verification.v1.VerificationService/GetInspectionResult',
            verification__service__pb2.GetSessionRequest.SerializeToString,
            verification__service__pb2.InspectionResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.verification.v1.VerificationService/HealthCheck',
            verification__service__pb2.HealthCheckRequest.SerializeToString,
            verification__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
