"""Initial organization schema

Revision ID: 20260203_0000
Revises: 
Create Date: 2026-02-03 00:00:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID


# revision identifiers, used by Alembic.
revision = '20260203_0000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('website_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata', JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('settings', JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='organization_service'
    )
    op.create_index(op.f('ix_organization_service_organizations_status'), 'organizations', ['status'], unique=False, schema='organization_service')
    op.create_index(op.f('ix_organization_service_organizations_slug'), 'organizations', ['slug'], unique=True, schema='organization_service')
    
    op.create_table('members',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_service.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='organization_service'
    )
    op.create_index(op.f('ix_organization_service_members_organization_id'), 'members', ['organization_id'], unique=False, schema='organization_service')
    op.create_index(op.f('ix_organization_service_members_status'), 'members', ['status'], unique=False, schema='organization_service')
    
    op.create_table('api_keys',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', ARRAY(sa.String), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_service.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='organization_service'
    )
    op.create_index(op.f('ix_organization_service_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False, schema='organization_service')
    op.create_index(op.f('ix_organization_service_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True, schema='organization_service')
    op.create_index(op.f('ix_organization_service_api_keys_status'), 'api_keys', ['status'], unique=False, schema='organization_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_service_api_keys_status'), table_name='api_keys', schema='organization_service')
    op.drop_index(op.f('ix_organization_service_api_keys_key_hash'), table_name='api_keys', schema='organization_service')
    op.drop_index(op.f('ix_organization_service_api_keys_organization_id'), table_name='api_keys', schema='organization_service')
    op.drop_table('api_keys', schema='organization_service')
    op.drop_index(op.f('ix_organization_service_members_status'), table_name='members', schema='organization_service')
    op.drop_index(op.f('ix_organization_service_members_organization_id'), table_name='members', schema='organization_service')
    op.drop_table('members', schema='organization_service')
    op.drop_index(op.f('ix_organization_service_organizations_slug'), table_name='organizations', schema='organization_service')
    op.drop_index(op.f('ix_organization_service_organizations_status'), table_name='organizations', schema='organization_service')
    op.drop_table('organizations', schema='organization_service')
    # ### end Alembic commands ###
