"""Initial presentation policy schema

Revision ID: cd86d0505323
Revises: 
Create Date: 2026-02-03 02:40:38.330301+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd86d0505323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('display_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_requirements', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('alternative_requirements', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_profile_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='presentation_policy_service'
    )
    op.create_index('ix_presentation_policies_org_status', 'presentation_policies', ['organization_id', 'status'], unique=False, schema='presentation_policy_service')
    op.create_index('ix_presentation_policies_organization_id', 'presentation_policies', ['organization_id'], unique=False, schema='presentation_policy_service')
    op.create_index('ix_presentation_policies_status', 'presentation_policies', ['status'], unique=False, schema='presentation_policy_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_presentation_policies_status', table_name='presentation_policies', schema='presentation_policy_service')
    op.drop_index('ix_presentation_policies_organization_id', table_name='presentation_policies', schema='presentation_policy_service')
    op.drop_index('ix_presentation_policies_org_status', table_name='presentation_policies', schema='presentation_policy_service')
    op.drop_table('presentation_policies', schema='presentation_policy_service')
    # ### end Alembic commands ###
