# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v1 import notification_service_pb2 as v1_dot_notification__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/notification_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationServiceStub(object):
    """NotificationService handles sending and managing in-app and external
    notifications (email, push, SMS, webhook).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNotification = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/SendNotification',
                request_serializer=v1_dot_notification__service__pb2.SendNotificationRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.GetNotification = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/GetNotification',
                request_serializer=v1_dot_notification__service__pb2.GetNotificationRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.ListNotifications = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/ListNotifications',
                request_serializer=v1_dot_notification__service__pb2.ListNotificationsRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.ListNotificationsResponse.FromString,
                _registered_method=True)
        self.GetUnreadCount = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/GetUnreadCount',
                request_serializer=v1_dot_notification__service__pb2.GetUnreadCountRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.GetUnreadCountResponse.FromString,
                _registered_method=True)
        self.MarkAsRead = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/MarkAsRead',
                request_serializer=v1_dot_notification__service__pb2.MarkAsReadRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.MarkAllAsRead = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/MarkAllAsRead',
                request_serializer=v1_dot_notification__service__pb2.MarkAllAsReadRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.MarkAllAsReadResponse.FromString,
                _registered_method=True)
        self.DeleteNotification = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/DeleteNotification',
                request_serializer=v1_dot_notification__service__pb2.DeleteNotificationRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.DeleteNotificationResponse.FromString,
                _registered_method=True)
        self.StreamNotifications = channel.unary_stream(
                '/marty.ui.notification.v1.NotificationService/StreamNotifications',
                request_serializer=v1_dot_notification__service__pb2.StreamNotificationsRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.NotificationEvent.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/marty.ui.notification.v1.NotificationService/HealthCheck',
                request_serializer=v1_dot_notification__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=v1_dot_notification__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """NotificationService handles sending and managing in-app and external
    notifications (email, push, SMS, webhook).
    """

    def SendNotification(self, request, context):
        """Send a notification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotification(self, request, context):
        """Get a notification by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotifications(self, request, context):
        """List notifications with optional filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnreadCount(self, request, context):
        """Get unread notification count for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAsRead(self, request, context):
        """Mark a notification as read.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAllAsRead(self, request, context):
        """Mark all matching notifications as read.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNotification(self, request, context):
        """Delete a notification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNotifications(self, request, context):
        """-- Streaming --

        Subscribe to real-time notification events for a recipient.
        Server pushes new notifications as they arrive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=v1_dot_notification__service__pb2.SendNotificationRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.NotificationResponse.SerializeToString,
            ),
            'GetNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotification,
                    request_deserializer=v1_dot_notification__service__pb2.GetNotificationRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.NotificationResponse.SerializeToString,
            ),
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=v1_dot_notification__service__pb2.ListNotificationsRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.ListNotificationsResponse.SerializeToString,
            ),
            'GetUnreadCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnreadCount,
                    request_deserializer=v1_dot_notification__service__pb2.GetUnreadCountRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.GetUnreadCountResponse.SerializeToString,
            ),
            'MarkAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAsRead,
                    request_deserializer=v1_dot_notification__service__pb2.MarkAsReadRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.NotificationResponse.SerializeToString,
            ),
            'MarkAllAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAllAsRead,
                    request_deserializer=v1_dot_notification__service__pb2.MarkAllAsReadRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.MarkAllAsReadResponse.SerializeToString,
            ),
            'DeleteNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNotification,
                    request_deserializer=v1_dot_notification__service__pb2.DeleteNotificationRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.DeleteNotificationResponse.SerializeToString,
            ),
            'StreamNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNotifications,
                    request_deserializer=v1_dot_notification__service__pb2.StreamNotificationsRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.NotificationEvent.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=v1_dot_notification__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=v1_dot_notification__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.ui.notification.v1.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.ui.notification.v1.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """NotificationService handles sending and managing in-app and external
    notifications (email, push, SMS, webhook).
    """

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/SendNotification',
            v1_dot_notification__service__pb2.SendNotificationRequest.SerializeToString,
            v1_dot_notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/GetNotification',
            v1_dot_notification__service__pb2.GetNotificationRequest.SerializeToString,
            v1_dot_notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/ListNotifications',
            v1_dot_notification__service__pb2.ListNotificationsRequest.SerializeToString,
            v1_dot_notification__service__pb2.ListNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnreadCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/GetUnreadCount',
            v1_dot_notification__service__pb2.GetUnreadCountRequest.SerializeToString,
            v1_dot_notification__service__pb2.GetUnreadCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/MarkAsRead',
            v1_dot_notification__service__pb2.MarkAsReadRequest.SerializeToString,
            v1_dot_notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkAllAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/MarkAllAsRead',
            v1_dot_notification__service__pb2.MarkAllAsReadRequest.SerializeToString,
            v1_dot_notification__service__pb2.MarkAllAsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/DeleteNotification',
            v1_dot_notification__service__pb2.DeleteNotificationRequest.SerializeToString,
            v1_dot_notification__service__pb2.DeleteNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/StreamNotifications',
            v1_dot_notification__service__pb2.StreamNotificationsRequest.SerializeToString,
            v1_dot_notification__service__pb2.NotificationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.ui.notification.v1.NotificationService/HealthCheck',
            v1_dot_notification__service__pb2.HealthCheckRequest.SerializeToString,
            v1_dot_notification__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
