pub const HTTP_ROUTES: &[(&str, &str)] = &[
    ("GET", "/v1/flows/capabilities"),
    ("POST", "/v1/flows/definitions"),
    ("GET", "/v1/flows/definitions"),
    ("GET", "/v1/flows/definitions/{flow_id}"),
    ("PATCH", "/v1/flows/definitions/{flow_id}"),
    ("POST", "/v1/flows/definitions/{flow_id}/validate"),
    ("POST", "/v1/flows/definitions/{flow_id}/test"),
    ("POST", "/v1/flows/definitions/{flow_id}/activate"),
    ("DELETE", "/v1/flows/definitions/{flow_id}"),
    ("POST", "/v1/flows/instances"),
    ("GET", "/v1/flows/instances"),
    ("GET", "/v1/flows/instances/{instance_id}"),
    ("GET", "/v1/flows/instances/{instance_id}/result"),
    ("POST", "/v1/flows/instances/{instance_id}/advance"),
    ("POST", "/v1/flows/instances/{instance_id}/cancel"),
    ("GET", "/v1/flows/instances/{instance_id}/artifacts"),
    (
        "GET",
        "/v1/flows/instances/{instance_id}/artifacts/{artifact_id}",
    ),
    ("POST", "/v1/flows/instances/{instance_id}/generate-qr"),
    ("POST", "/v1/flows/verify"),
    ("GET", "/oid4vp/did.json"),
    ("POST", "/v1/flows/instances/{instance_id}/submit"),
    ("POST", "/v1/flows/instances/{instance_id}/submit/dc-api"),
    ("POST", "/v1/flows/siop"),
    ("POST", "/v1/flows/siop/submit"),
    ("POST", "/v1/flows/webhooks/application-approved"),
    ("GET", "/health/native-backend"),
];

pub const GRPC_METHODS: &[&str] = &[
    "CreateFlowDefinition",
    "GetFlowDefinition",
    "ListFlowDefinitions",
    "ActivateFlowDefinition",
    "DeleteFlowDefinition",
    "StartFlowInstance",
    "GetFlowInstance",
    "ListFlowInstances",
    "AdvanceFlowInstance",
    "CancelFlowInstance",
    "GetFlowResult",
    "ListFlowArtifacts",
    "StartVerification",
    "ApplicationApproved",
    "StreamFlowUpdates",
    "HealthCheck",
];
