#!/bin/sh
set -e

PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-prod.example.com}
UI_UPSTREAM=${UI_UPSTREAM:-ui:80}
GATEWAY_UPSTREAM=${GATEWAY_UPSTREAM:-gateway:8000}
FLOW_UPSTREAM=${FLOW_UPSTREAM:-flow:8011}
KEYCLOAK_UPSTREAM=${KEYCLOAK_UPSTREAM:-keycloak:8080}
CANVAS_REAL_PUBLIC_HOST=${CANVAS_REAL_PUBLIC_HOST:-canvas-test.${PUBLIC_DOMAIN}}
CANVAS_SANDBOX_PUBLIC_HOST=${CANVAS_SANDBOX_PUBLIC_HOST:-canvas-sandbox.${PUBLIC_DOMAIN}}

echo "Configuring self-host nginx..."
echo "  PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}"
echo "  UI_UPSTREAM: ${UI_UPSTREAM}"
echo "  GATEWAY_UPSTREAM: ${GATEWAY_UPSTREAM}"
echo "  FLOW_UPSTREAM: ${FLOW_UPSTREAM}"
echo "  KEYCLOAK_UPSTREAM: ${KEYCLOAK_UPSTREAM}"
echo "  CANVAS_REAL_PUBLIC_HOST: ${CANVAS_REAL_PUBLIC_HOST}"
echo "  CANVAS_SANDBOX_PUBLIC_HOST: ${CANVAS_SANDBOX_PUBLIC_HOST}"

envsubst '${PUBLIC_DOMAIN} ${UI_UPSTREAM} ${GATEWAY_UPSTREAM} ${FLOW_UPSTREAM} ${KEYCLOAK_UPSTREAM} ${CANVAS_REAL_PUBLIC_HOST} ${CANVAS_SANDBOX_PUBLIC_HOST}' \
  < /etc/nginx/conf.d/default.conf.template \
  > /etc/nginx/conf.d/default.conf

echo "Generated self-host nginx configuration"
nginx -t
