"""Initial flow schema

Revision ID: 1854c4083445
Revises: 
Create Date: 2026-02-03 02:48:48.573519+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1854c4083445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('flow_type', sa.String(length=50), nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('transitions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('start_step_id', sa.String(length=36), nullable=True),
    sa.Column('credential_template_id', sa.String(length=36), nullable=True),
    sa.Column('presentation_policy_id', sa.String(length=36), nullable=True),
    sa.Column('deployment_profile_id', sa.String(length=36), nullable=True),
    sa.Column('default_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('enable_resume', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flow_service'
    )
    op.create_index('ix_flow_definitions_flow_type', 'flow_definitions', ['flow_type'], unique=False, schema='flow_service')
    op.create_index('ix_flow_definitions_org_status', 'flow_definitions', ['organization_id', 'status'], unique=False, schema='flow_service')
    op.create_index('ix_flow_definitions_organization_id', 'flow_definitions', ['organization_id'], unique=False, schema='flow_service')
    op.create_index('ix_flow_definitions_status', 'flow_definitions', ['status'], unique=False, schema='flow_service')
    op.create_table('flow_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_definition_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step_id', sa.String(length=36), nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('step_history', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flow_service'
    )
    op.create_index('ix_flow_instances_external_reference', 'flow_instances', ['external_reference'], unique=False, schema='flow_service')
    op.create_index('ix_flow_instances_flow_definition_id', 'flow_instances', ['flow_definition_id'], unique=False, schema='flow_service')
    op.create_index('ix_flow_instances_organization_id', 'flow_instances', ['organization_id'], unique=False, schema='flow_service')
    op.create_index('ix_flow_instances_status', 'flow_instances', ['status'], unique=False, schema='flow_service')
    op.create_index('ix_flow_instances_subject_id', 'flow_instances', ['subject_id'], unique=False, schema='flow_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_instances_subject_id', table_name='flow_instances', schema='flow_service')
    op.drop_index('ix_flow_instances_status', table_name='flow_instances', schema='flow_service')
    op.drop_index('ix_flow_instances_organization_id', table_name='flow_instances', schema='flow_service')
    op.drop_index('ix_flow_instances_flow_definition_id', table_name='flow_instances', schema='flow_service')
    op.drop_index('ix_flow_instances_external_reference', table_name='flow_instances', schema='flow_service')
    op.drop_table('flow_instances', schema='flow_service')
    op.drop_index('ix_flow_definitions_status', table_name='flow_definitions', schema='flow_service')
    op.drop_index('ix_flow_definitions_organization_id', table_name='flow_definitions', schema='flow_service')
    op.drop_index('ix_flow_definitions_org_status', table_name='flow_definitions', schema='flow_service')
    op.drop_index('ix_flow_definitions_flow_type', table_name='flow_definitions', schema='flow_service')
    op.drop_table('flow_definitions', schema='flow_service')
    # ### end Alembic commands ###
