"""Initial trust profile schema

Revision ID: 33f047612e9b
Revises: 
Create Date: 2026-02-03 02:04:41.004460+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '33f047612e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trust_sources', sa.JSON(), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=False),
    sa.Column('revocation_policy', sa.JSON(), nullable=False),
    sa.Column('revocation_profile_id', sa.String(), nullable=True),
    sa.Column('time_policy', sa.JSON(), nullable=False),
    sa.Column('supported_formats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trust_profile_service'
    )
    op.create_index('ix_trust_profiles_org_status', 'trust_profiles', ['organization_id', 'status'], unique=False, schema='trust_profile_service')
    op.create_index('ix_trust_profiles_organization_id', 'trust_profiles', ['organization_id'], unique=False, schema='trust_profile_service')
    op.create_index('ix_trust_profiles_status', 'trust_profiles', ['status'], unique=False, schema='trust_profile_service')
    op.create_table('trusted_issuers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trust_profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('issuer_did', sa.String(), nullable=False),
    sa.Column('issuer_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credential_template_ids', sa.JSON(), nullable=False),
    sa.Column('verification_keys', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trust_profile_service'
    )
    op.create_index('ix_trusted_issuers_issuer_did', 'trusted_issuers', ['issuer_did'], unique=False, schema='trust_profile_service')
    op.create_index('ix_trusted_issuers_status', 'trusted_issuers', ['status'], unique=False, schema='trust_profile_service')
    op.create_index('ix_trusted_issuers_trust_profile_id', 'trusted_issuers', ['trust_profile_id'], unique=False, schema='trust_profile_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trusted_issuers_trust_profile_id', table_name='trusted_issuers', schema='trust_profile_service')
    op.drop_index('ix_trusted_issuers_status', table_name='trusted_issuers', schema='trust_profile_service')
    op.drop_index('ix_trusted_issuers_issuer_did', table_name='trusted_issuers', schema='trust_profile_service')
    op.drop_table('trusted_issuers', schema='trust_profile_service')
    op.drop_index('ix_trust_profiles_status', table_name='trust_profiles', schema='trust_profile_service')
    op.drop_index('ix_trust_profiles_organization_id', table_name='trust_profiles', schema='trust_profile_service')
    op.drop_index('ix_trust_profiles_org_status', table_name='trust_profiles', schema='trust_profile_service')
    op.drop_table('trust_profiles', schema='trust_profile_service')
    # ### end Alembic commands ###
